// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9gvW-dU9mIvboo_NaVjQw6P0jaaNOx0',
    appId: '1:414414311995:web:39db22515ff5ae45b7421e',
    messagingSenderId: '414414311995',
    projectId: 'wuuthrad-b73d5',
    authDomain: 'wuuthrad-b73d5.firebaseapp.com',
    storageBucket: 'wuuthrad-b73d5.appspot.com',
    measurementId: 'G-X2J0M4RLXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ywGqDvRs7aBZiUFKG4XeaTBbH9-5ZIU',
    appId: '1:414414311995:android:5ecab3d9f3d2f830b7421e',
    messagingSenderId: '414414311995',
    projectId: 'wuuthrad-b73d5',
    storageBucket: 'wuuthrad-b73d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBQRXE3Vk_RAdq8sG7_vrUnM9qGdV-lg',
    appId: '1:414414311995:ios:cf35bf04513ac155b7421e',
    messagingSenderId: '414414311995',
    projectId: 'wuuthrad-b73d5',
    storageBucket: 'wuuthrad-b73d5.appspot.com',
    iosClientId:
        '414414311995-bko23fdnuah73fm8h4r03f3bvl1l4r90.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVBQRXE3Vk_RAdq8sG7_vrUnM9qGdV-lg',
    appId: '1:414414311995:ios:cf35bf04513ac155b7421e',
    messagingSenderId: '414414311995',
    projectId: 'wuuthrad-b73d5',
    storageBucket: 'wuuthrad-b73d5.appspot.com',
    iosClientId:
        '414414311995-bko23fdnuah73fm8h4r03f3bvl1l4r90.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydev',
  );
}
